apiVersion: apps/v1
kind: Deployment
metadata:
  name: fearsome-fish
  namespace: app-foo-prd
  labels:
    app: fearsome-fish
    env: prd
spec:
  #replicas: 1  # Using an HPA so leave this set to '1'
  selector:
    matchLabels:
      app: fearsome-fish
      env: prd
  template:
    metadata:
      labels:
        app: fearsome-fish
        env: prd
    spec:
      containers:
      - name: container1
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
